import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/custom/session-provider";
import TRPCProvider from "@/lib/trpc/trpc-provider";
import { getDefaultLanguage } from "@/lib/i18n/settings";
import I18nProvider from "@/components/custom/i18n-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  const defaultLanguage = getDefaultLanguage();

  return (
    <html lang={defaultLanguage}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <I18nProvider initialLang={defaultLanguage}>
            <TRPCProvider>{children}</TRPCProvider>
          </I18nProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
