/**
 * Localized Link Component
 * A wrapper around Next.js Link component that preserves language preferences
 *
 * Generated by Copilot
 */

"use client";

import { ReactNode } from "react";
import Link from "next/link";
import { useTranslation } from "react-i18next";

/**
 * Props for the LocalizedLink component
 */
interface LocalizedLinkProps {
  /** Destination path */
  href: string;
  /** Link content */
  children: ReactNode;
  /** Additional CSS classes */
  className?: string;
  /** Whether to apply active link styles */
  isActive?: boolean;
}

/**
 * A localized link component that preserves language preferences
 */
export default function LocalizedLink({
  href,
  children,
  className = "",
  isActive = false,
}: LocalizedLinkProps) {
  const { i18n } = useTranslation();

  // Add active class if the link is active
  const activeClass = isActive ? "font-bold" : "";

  return (
    <Link
      href={href}
      className={`${className} ${activeClass}`}
      locale={i18n.language}
    >
      {children}
    </Link>
  );
}
