/**
 * i18n storage utilities for persisting language preferences
 *
 * Generated by Copilot
 */

"use client";

import { isLanguageSupported, getDefaultLanguage } from "./settings";

// Local storage keys
const LANGUAGE_PREFERENCE_KEY = "i18nextLng";

/**
 * Save the user's language preference to local storage
 *
 * @param languageCode - The language code to save (e.g., 'en', 'fr')
 * @returns True if successfully saved, false otherwise
 */
export function saveLanguagePreference(languageCode: string): boolean {
  if (typeof window === "undefined") {
    return false;
  }

  try {
    // Only save supported languages
    if (isLanguageSupported(languageCode)) {
      localStorage.setItem(LANGUAGE_PREFERENCE_KEY, languageCode);
      return true;
    }
    return false;
  } catch (error) {
    console.error("Failed to save language preference:", error);
    return false;
  }
}

/**
 * Retrieve the user's language preference from local storage
 *
 * @returns The saved language code or null if not found
 */
export function getLanguagePreference(): string | null {
  if (typeof window === "undefined") {
    return null;
  }

  try {
    const languageCode = localStorage.getItem(LANGUAGE_PREFERENCE_KEY);

    // Validate the stored language is still supported
    if (languageCode && isLanguageSupported(languageCode)) {
      return languageCode;
    }

    return null;
  } catch (error) {
    console.error("Failed to retrieve language preference:", error);
    return null;
  }
}

/**
 * Clear the user's language preference from local storage
 *
 * @returns True if successfully cleared, false otherwise
 */
export function clearLanguagePreference(): boolean {
  if (typeof window === "undefined") {
    return false;
  }

  try {
    localStorage.removeItem(LANGUAGE_PREFERENCE_KEY);
    return true;
  } catch (error) {
    console.error("Failed to clear language preference:", error);
    return false;
  }
}

/**
 * Get the effective language to use
 * Checks local storage first, then falls back to default language
 *
 * @returns The language code to use
 */
export function getEffectiveLanguage(): string {
  return getLanguagePreference() || getDefaultLanguage();
}
